version: '3.8'

services:
  api:
    build: .
    ports:
      - "6060:6060"
    volumes:
      - .:/var/www
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d
    restart: always
    networks:
      - api

  db:
    image: mysql
    container_name: mysql_database
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  database_data:
