<?php
namespace src\Enums;

enum ErrorTypes {
   case UNKNOWN_METHOD;
   case UNKNOWN_SERVER_REQUEST;
   case EMPTY_REQUEST;
   case UNSUPPORTED_PATH;
   case WRONG_DATA_TYPE;
   case INVALID_RANGE_NUMBER;
   case REQUEST_REQUIREMENTS_NOT_MET;
   case USER_WRONG_PASSWORD;
   case USER_WRONG_TOKEN;
   case USER_ALREADY_REGISTERED;
   case AUTH_COOKIE_NOT_PASSED;
   case AUTH_COOKIE_NOT_SATISFIED;
   case UNKNOWN_USER;
   case MODEL_NOT_FOUND;
   case UNAUTHORIZED;
   case INTERNAL_SERVER_ERROR;
   
}